### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by stevecooperorg** [skyzyx/alpine-pandoc#1]
Hi - this looks like a really useful bit of work, and I'd like to base a quick doc compiler project idea off of it, but the project doesn't have a license. Could you clarify the license you're putting this out under, or are you reserving copyright? Thanks.

**Comment by skyzyx** [comment]
You're right. My bad. My intention is something _Open-Source_, and not _Free Software_.

For something this simple, I'm gonna say MIT. Let me add a `LICENSE` file.

**Comment by stevecooperorg** [comment]
That’s amazing! Thanks.
